name: Download Release dn_pico_example

# Controls when the workflow will run
on: push

jobs:  
  get_asset:
    runs-on: ubuntu-latest
    steps:
      - name: List Releases
        run: gh release list --repo danou22/bun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch asset
        run: gh run download danou22/bun -n "bun-test_version.zip" --dir latest_test 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: See what we downloaded
        run: ls

      #- name: Inspect content
      #  run: cat hello.txt
