name: Download Release example

# Controls when the workflow will run
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  get_asset:
    runs-on: ubuntu-latest
    steps:
      - name: List Releases
        run: gh release list --repo danou22/bun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch asset
        #run: gh run download ${{ github.run_id }} --repo danou22/bun --dir latest_test 
        run: gh release download --repo danou22/bun test version --dir rel_package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: See what we downloaded
        run: ls

      #- name: Inspect content
      #  run: cat hello.txt
